In [1]:
# import project directory helper
import os, sys
ROOT_DIR = os.path.abspath('/home/hduser/document/jupyter/FYP/') 
sys.path.insert(0, ROOT_DIR)

In [2]:
# import pyspark packages
# from pyspark import SparkContext
# from pyspark.sql import SQLContext
# set the kafka dependencies before create spark context or session
import os
os.environ[
    'PYSPARK_SUBMIT_ARGS'] = '--packages org.apache.spark:spark-streaming-kafka-0-8_2.11:2.4.4,org.apache.spark:spark-sql-kafka-0-10_2.11:2.4.4 pyspark-shell'
from pyspark.sql import SparkSession, functions, types
from pyspark.sql.types import *

In [3]:
# import util packages
from IPython.display import display
import pandas as pd

In [4]:
spark = SparkSession.builder.appName('attraction').getOrCreate()
spark

In [5]:
# define path
tripad_attr_path = ROOT_DIR + '/crawler/datasets/tripadvisor_dataset/attractions/'
parquet_path = ROOT_DIR + '/crawler/datasets/tripadvisor_dataset/spark/'

# Attraction Details

In [6]:
# read spark dataframe from parquet
final_attr_spark_df = spark.read.parquet(parquet_path + 'tripad_attr')

## Processing category

In [7]:
def get_cat(x):
    if isinstance(x, list):
        return x[0]
    else:
        return x

In [8]:
get_category_udf = functions.udf(lambda x: get_cat(x), StringType())

In [9]:
final_attr_spark_df = final_attr_spark_df.withColumn(
    'updated_category', get_category_udf(final_attr_spark_df.category))

In [10]:
final_attr_spark_df = final_attr_spark_df.drop('category')
final_attr_spark_df = final_attr_spark_df.withColumnRenamed('updated_category', 'category')

In [11]:
# visualize spark dataframe
display(final_attr_spark_df.count())
final_attr_spark_df.printSchema()
display(final_attr_spark_df.toPandas())

4257

root
 |-- activityId: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- country: string (nullable = true)
 |-- latitude: string (nullable = true)
 |-- longitude: string (nullable = true)
 |-- name: string (nullable = true)
 |-- price: double (nullable = true)
 |-- rating: double (nullable = true)
 |-- category: string (nullable = true)

,activityId,city,state,country,latitude,longitude,name,price,rating,category
0,12962337,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Malaysia Countryside and Batu Caves Tour from ...,43.27,4.5,featured_tours_and_tickets
1,12905660,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Petronas Twin Towers Admission Tickets (E-Tick...,119.49,4.0,featured_tours_and_tickets
2,11807013,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Discover the Best Local Food Tour by Night in ...,142.75,4.5,featured_tours_and_tickets
3,12471375,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Genting Highlands Day Trip from Kuala Lumpur w...,103.01,4.5,featured_tours_and_tickets
4,12469580,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Half-Day Kuala Lumpur City Tour,43.27,4.0,featured_tours_and_tickets
5,16722683,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,KL Hop On Hop Off City Tour,53.07,3.0,featured_tours_and_tickets
6,11454341,Kuah,Langkawi,Malaysia,6.326672,99.843025,Langkawi Archipelago Jet Ski Tour Including Da...,515.06,5.0,featured_tours_and_tickets
7,11812460,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Private Half-Day Batu Caves Waterfalls and Hot...,377.67,5.0,featured_tours_and_tickets
8,11992275,Kuah,Langkawi,Malaysia,6.326672,99.843025,12 Flights: Zipline Eco Adventure in Langkawi,473.86,5.0,featured_tours_and_tickets
9,11991123,Penang Island,Penang,Malaysia,5.388071,100.29352,Cheong Fatt Tze George Town Penang: The Blue M...,20.61,4.5,featured_tours_and_tickets
10,11482502,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Batik Bag Painting Workshop by myBatik,119.49,5.0,featured_tours_and_tickets
11,19350513,Batu Ferringhi,Penang Island,Malaysia,5.471783,100.24629,Chef Samuel's Private Malaysian Cooking Class,700.48,5.0,featured_tours_and_tickets
12,11474972,George Town,Penang Island,Malaysia,5.411938,100.32664,Half-Day Penang Countryside Cycling Tour,115.81,5.0,featured_tours_and_tickets
13,12648212,Kota Kinabalu,Kota Kinabalu District,Malaysia,5.979383,116.07349,North Borneo Cruises City Night Dinner Cruise,222.48,4.5,featured_tours_and_tickets
14,11470871,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Hot Air Balloon Flight over Serdang,947.71,5.0,featured_tours_and_tickets
15,12468200,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Private Tour: Kuala Lumpur with Petronas Twin ...,407.98,5.0,featured_tours_and_tickets
16,12934938,Sandakan,Sandakan Division,Malaysia,5.838944,118.11561,Kinabatangan River Cruise,568.63,5.0,featured_tours_and_tickets
17,11452959,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Small-Group Food Trail Walking Tour in Kuala L...,243.14,5.0,featured_tours_and_tickets
18,16749910,Langkawi,Langkawi District,Malaysia,6.351074,99.75824,Langkawi Half Day Island Hoping Tour- Sharing ...,74.18,4.0,featured_tours_and_tickets
19,12939362,Sandakan,Sandakan Division,Malaysia,5.838944,118.11561,"Private Full Day Sepilok Orang Utan, Bornean S...",412.11,4.5,featured_tours_and_tickets
20,15135878,Kota Kinabalu,Kota Kinabalu District,Malaysia,5.979383,116.07349,Island Hopping,226.63,4.5,featured_tours_and_tickets
21,15142299,Kota Kinabalu,Kota Kinabalu District,Malaysia,5.979383,116.07349,Full Day Walk in Kinbalu Park and Poring Hot S...,246.87,4.5,featured_tours_and_tickets
22,11449679,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Batu Caves Tour from Kuala Lumpur,54.97,3.5,featured_tours_and_tickets
23,15830443,Penang Island,Penang,Malaysia,5.388071,100.29352,Batu Ferringhi's hidden gems,144.22,5.0,featured_tours_and_tickets
24,11484318,Petaling Jaya,Petaling District,Malaysia,3.10363,101.64778,Sunway Lagoon Malaysia One-Day Pass,177.18,4.0,featured_tours_and_tickets
25,16939354,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,KL Hop On Hop Off Bus Pass,61.81,4.0,featured_tours_and_tickets
26,14061658,Langkawi,Langkawi District,Malaysia,6.351074,99.75824,Private Day Tour of Langkawi with Cable Car an...,309.04,2.5,featured_tours_and_tickets
27,17718163,George Town,Penang Island,Malaysia,5.411938,100.32664,Penang: Flexible 6-Hours Highlights,309.04,5.0,featured_tours_and_tickets
28,11475887,Cherating,Kuantan District,Malaysia,4.133792,103.38026,Fireflies Tour in Cherating,63.87,4.5,featured_tours_and_tickets
29,17419599,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Cooler Lumpur by Night Vespa Food Tour by Vesp...,412.05,5.0,featured_tours_and_tickets
...,...,...,...,...,...,...,...,...,...,...
4227,17685131,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Vacation Photographer in Putrajaya,1008.66,-1.0,tours_sightseeing
4228,13807388,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,KL Butterfly Park Admission Ticket & Free Kual...,164.84,5.0,tours_sightseeing
4229,14017942,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Segway Adventure - Eco Ride Tour of Perdana Bo...,381.20,-1.0,tours_sightseeing
4230,14779089,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Full Day Tour at Tadom Hill Resort from Kuala ...,346.17,-1.0,tours_sightseeing
4231,17847022,Johor Bahru,Johor Bahru District,Malaysia,1.473394,103.75248,Private Photo Session with a Local Photographe...,1008.66,-1.0,tours_sightseeing
4232,17847038,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Private Photo Session with a Local Photographe...,1008.66,-1.0,tours_sightseeing
4233,17847107,Batu Ferringhi,Penang Island,Malaysia,5.471783,100.24629,Private Photo Session with a Local Photographe...,1008.66,-1.0,tours_sightseeing
4234,11479905,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Private Tour: Historical Malacca Trip from Kua...,391.50,5.0,tours_sightseeing
4235,14025818,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Guided Eco Ride Tour of City in the Garden Put...,480.10,-1.0,tours_sightseeing
4236,17329973,Petaling Jaya,Petaling District,Malaysia,3.10363,101.64778,Sky Mirror and Paddy Field Tour,391.50,-1.0,tours_sightseeing
4237,17019216,Batu Ferringhi,Penang Island,Malaysia,5.471783,100.24629,Team Building & Activities Heritage City Penang,267.87,-1.0,tours_sightseeing
4238,17019215,Batu Ferringhi,Penang Island,Malaysia,5.471783,100.24629,Team Building & Activities Beach Penang,304.96,-1.0,tours_sightseeing
4239,12470359,Batu Ferringhi,Penang Island,Malaysia,5.471783,100.24629,Private Half-Day Penang Cultural Experience,133.93,-1.0,tours_sightseeing
4240,14787807,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Kuala Lumpur Cruise Layover Tour from Boustead...,387.38,-1.0,tours_sightseeing
4241,12467426,Sarawak,Malaysia,Malaysia,2.310777,112.50697,Half-Day Sightseeing Tour of Miri City,182.11,4.0,tours_sightseeing
4242,11464516,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Taman Negara National Park + Cameron Highlands...,2616.87,-1.0,tours_sightseeing
4243,12468974,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Full-Day Kuala Lumpur Grand Tour with Lunch,247.26,3.5,tours_sightseeing
4244,12464505,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Malaysian Cultural Night in Kuala Lumpur,247.26,4.0,tours_sightseeing
4245,12469002,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Half-Day City Tour with Kuala Lumpur Tower Adm...,226.66,-1.0,tours_sightseeing
4246,12943485,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Escape Room: Malaysia's First Real Life Escape...,33.38,4.5,tours_sightseeing
4247,13857449,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Private Kuala Lumpur Heritage Walking Tour,164.84,-1.0,tours_sightseeing
4248,15040147,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,"Cameron Highlands Day Tour Strawberry Park, Te...",576.95,-1.0,tours_sightseeing
4249,15040146,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Historical Malacca Full-day Tour with Lunch,366.77,-1.0,tours_sightseeing
4250,17486540,Petaling Jaya,Petaling District,Malaysia,3.10363,101.64778,4G WiFi (MY Airport Pick Up) for Malaysia,34.41,-1.0,tours_sightseeing
4251,17486534,Johor Bahru,Johor Bahru District,Malaysia,1.473394,103.75248,5D Studio Admission Ticket,22.86,-1.0,tours_sightseeing
4252,17486546,Kuah,Langkawi,Malaysia,6.326672,99.843025,6D Cinemotion Admission Ticket,19.05,-1.0,tours_sightseeing
4253,12464599,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Kuala Lumpur City Tour,98.91,2.5,tours_sightseeing
4254,11481439,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Kuala Lumpur City Tour + Batu cave Tour - 1 Day,576.95,5.0,tours_sightseeing
4255,12043816,Batu Ferringhi,Penang Island,Malaysia,5.471783,100.24629,Penang Amazing Race,267.87,1.0,tours_sightseeing
4256,14187878,Kuching,Sarawak,Malaysia,1.52022,110.35362,Mangrove & Irrawaddy Dolphin Watching Cruise f...,230.78,5.0,tours_sightseeing

In [12]:
# create table or view from spark dataframe
final_attr_spark_df.createOrReplaceTempView('final_attr_spark_df')

## Processing city

In [13]:
# create spark user defined function
clean_string_udf = functions.udf(lambda x: '_'.join(x.split(' ')).lower(), StringType())

In [14]:
# final_attr_spark_df = final_attr_spark_df.withColumn(
#     'city', clean_string_udf(final_attr_spark_df.city))

## Processing rating

In [15]:
# show null row from spark dataframe basec on specific column
final_attr_spark_df.where(final_attr_spark_df.rating.isNull()).show()
final_attr_spark_df.count()

+----------+----+-----+-------+--------+---------+----+-----+------+--------+
|activityId|city|state|country|latitude|longitude|name|price|rating|category|
+----------+----+-----+-------+--------+---------+----+-----+------+--------+
+----------+----+-----+-------+--------+---------+----+-----+------+--------+

4257

In [16]:
# set a constant or literal value to null fields (for showing, if needed update as required)
temp_spark_df = final_attr_spark_df.where(
    final_attr_spark_df.rating.isNull()).withColumn("rating",
                                                    functions.lit(-1))

final_attr_spark_df = final_attr_spark_df.where(
    final_attr_spark_df.rating.isNotNull()).union(temp_spark_df)

final_attr_spark_df.count()

4257

###### Recalculate for those field with -1 rating value based on category

In [17]:
attr_rating_spark_df = final_attr_spark_df

In [18]:
avg_rat_spark_df = spark.sql(
    "SELECT category, AVG(rating) as avg_rating FROM final_attr_spark_df WHERE rating != -1 GROUP BY category"
)
avg_rat_spark_df.show()

+--------------------+------------------+
|            category|        avg_rating|
+--------------------+------------------+
|air_helicopter_ba...|               5.0|
|   classes_workshops|              3.75|
|   tours_sightseeing| 4.103448275862069|
|featured_tours_an...| 4.483333333333333|
|walking_biking_tours| 4.688679245283019|
|        water_sports|              4.13|
| food_wine_nightlife| 4.208333333333333|
|    shopping_fashion|               4.5|
|day_trips_excursions|              4.22|
|transfers_ground_...|4.5523255813953485|
|shows_concerts_sp...|3.3333333333333335|
|  outdoor_activities| 4.443661971830986|
|   local_experiences|            4.6875|
|         theme_parks| 3.526315789473684|
|cruises_sailing_w...|              3.75|
|luxury_special_oc...| 4.141025641025641|
|    shore_excursions| 4.090909090909091|
|     family_friendly|3.8275862068965516|
|multiday_extended...|             4.375|
|sightseeing_ticke...| 4.038461538461538|
+--------------------+------------------+
only showing top 20 rows

In [19]:
def roundTo5(x, base=.5):
    return float(round(x / base) * base)
round_to_5_udf = functions.udf(lambda x: roundTo5(x), DoubleType())

In [20]:
avg_rat_spark_df = avg_rat_spark_df.withColumn(
    'updated_rating', round_to_5_udf(avg_rat_spark_df.avg_rating))
avg_rat_spark_df.show()

+--------------------+------------------+--------------+
|            category|        avg_rating|updated_rating|
+--------------------+------------------+--------------+
|air_helicopter_ba...|               5.0|           5.0|
|   classes_workshops|              3.75|           4.0|
|   tours_sightseeing| 4.103448275862069|           4.0|
|featured_tours_an...| 4.483333333333333|           4.5|
|walking_biking_tours| 4.688679245283019|           4.5|
|        water_sports|              4.13|           4.0|
| food_wine_nightlife| 4.208333333333333|           4.0|
|    shopping_fashion|               4.5|           4.5|
|day_trips_excursions|              4.22|           4.0|
|transfers_ground_...|4.5523255813953485|           4.5|
|shows_concerts_sp...|3.3333333333333335|           3.5|
|  outdoor_activities| 4.443661971830986|           4.5|
|   local_experiences|            4.6875|           4.5|
|         theme_parks| 3.526315789473684|           3.5|
|cruises_sailing_w...|              3.75|           4.0|
|luxury_special_oc...| 4.141025641025641|           4.0|
|    shore_excursions| 4.090909090909091|           4.0|
|     family_friendly|3.8275862068965516|           4.0|
|multiday_extended...|             4.375|           4.5|
|sightseeing_ticke...| 4.038461538461538|           4.0|
+--------------------+------------------+--------------+
only showing top 20 rows

In [21]:
attr_rating_spark_df = attr_rating_spark_df.join(avg_rat_spark_df,
                                                 ['category'], 'left')
attr_rating_spark_df.count()

4257

In [22]:
attr_rating_spark_df = attr_rating_spark_df.withColumn(
    "rating",
    functions.when(attr_rating_spark_df["rating"] == -1,
                   attr_rating_spark_df["updated_rating"]).otherwise(
                       attr_rating_spark_df["rating"])).drop(
                           'updated_rating', 'avg_rating')

In [23]:
# show null row from spark dataframe basec on specific column
attr_rating_spark_df.count()
display(attr_rating_spark_df.where(attr_rating_spark_df.rating.isNull()).toPandas())

,category,activityId,city,state,country,latitude,longitude,name,price,rating
0,weddings_honeymoons,19530324,Kuala Lumpur,Wilayah Persekutuan,Malaysia,3.156802,101.69717,Things to do in Kuala Lumpur - Book a photoshoot,593.43,None
1,weddings_honeymoons,19267760,Langkawi,Langkawi District,Malaysia,6.351074,99.75824,Private Explorer Boat - Langkawi Geopark Islan...,679.97,None
2,weddings_honeymoons,19267759,Langkawi,Langkawi District,Malaysia,6.351074,99.75824,Private Day Cruise,4945.27,None
3,weddings_honeymoons,15342175,Port Klang,Selangor,Malaysia,2.999852,101.39283,3 Nights 4 Days Honeymoon in Malaysia,618.16,None
4,weddings_honeymoons,17335319,Batu Ferringhi,Penang Island,Malaysia,5.471783,100.24629,Beach Wedding,24726.36,None

In [24]:
attr_rating_spark_df.createOrReplaceTempView('final_attr_spark_df')

###### Recalculate for those field with NaN rating value based on city

In [25]:
avg_rat_spark_df = spark.sql(
    "SELECT city, AVG(rating) as avg_rating FROM final_attr_spark_df WHERE rating is not NULL GROUP BY city"
)
avg_rat_spark_df.show()

+-------------+-----------------+
|         city|       avg_rating|
+-------------+-----------------+
|  Kuala Tahan|              4.5|
|     Bongawan|              5.0|
|   Georgetown|              4.5|
|       Sepang|4.468421052631579|
|       Ampang|              2.5|
|    Cherating|            4.425|
|  Kuala Kurau|              4.0|
|    Singapore|4.409090909090909|
|     Malaysia|4.323529411764706|
|   Katunayake|              4.0|
|      Salalah|              4.0|
|      Beijing|             4.75|
|       Melaka|4.271028037383178|
|    Tamparuli|              4.5|
|Petaling Jaya|         4.390625|
|  George Town| 4.27536231884058|
|  Kota Tinggi|              4.0|
|    Penampang|              4.0|
|      Sematan|              4.0|
|  Bayan Lepas|              4.6|
+-------------+-----------------+
only showing top 20 rows

In [26]:
def roundTo5(x, base=.5):
    return float(round(x / base) * base)
round_to_5_udf = functions.udf(lambda x: roundTo5(x), DoubleType())

In [27]:
avg_rat_spark_df = avg_rat_spark_df.withColumn(
    'updated_rating', round_to_5_udf(avg_rat_spark_df.avg_rating))
avg_rat_spark_df.show()

+-------------+-----------------+--------------+
|         city|       avg_rating|updated_rating|
+-------------+-----------------+--------------+
|  Kuala Tahan|              4.5|           4.5|
|     Bongawan|              5.0|           5.0|
|   Georgetown|              4.5|           4.5|
|       Sepang|4.468421052631579|           4.5|
|       Ampang|              2.5|           2.5|
|    Cherating|            4.425|           4.5|
|  Kuala Kurau|              4.0|           4.0|
|    Singapore|4.409090909090909|           4.5|
|     Malaysia|4.323529411764706|           4.5|
|   Katunayake|              4.0|           4.0|
|      Salalah|              4.0|           4.0|
|      Beijing|             4.75|           5.0|
|       Melaka|4.271028037383178|           4.5|
|    Tamparuli|              4.5|           4.5|
|Petaling Jaya|         4.390625|           4.5|
|  George Town| 4.27536231884058|           4.5|
|  Kota Tinggi|              4.0|           4.0|
|    Penampang|              4.0|           4.0|
|      Sematan|              4.0|           4.0|
|  Bayan Lepas|              4.6|           4.5|
+-------------+-----------------+--------------+
only showing top 20 rows

In [28]:
attr_rating_spark_df = attr_rating_spark_df.join(avg_rat_spark_df, ['city'],
                                                 'left')
attr_rating_spark_df.count()

4257

In [29]:
attr_rating_spark_df = attr_rating_spark_df.withColumn(
    "rating",
    functions.when(attr_rating_spark_df.rating.isNull(),
                   attr_rating_spark_df["updated_rating"]).otherwise(
                       attr_rating_spark_df["rating"])).drop(
                           'updated_rating', 'avg_rating')

In [30]:
# show null row from spark dataframe basec on specific column
attr_rating_spark_df.count()
display(attr_rating_spark_df.where(attr_rating_spark_df.rating.isNull()).toPandas())

Empty DataFrame
Columns: [city, category, activityId, state, country, latitude, longitude, name, price, rating]
Index: []

In [31]:
display(attr_rating_spark_df.toPandas())

,city,category,activityId,state,country,latitude,longitude,name,price,rating
0,Bongawan,cruises_sailing_water_tours,17683780,Sabah,Malaysia,5.507984,115.87458,Sky-Mirror Photographing and Proboscis Monkey...,164.84,5.0
1,Georgetown,sightseeing_tickets_passes,12990313,Demerara-Mahaica,Guyana,6.8,-58.1667,Colonial Penang Museum Admission Ticket,29.26,4.5
2,Kuala Tahan,multiday_extended_tours,14911433,Jerantut District,Malaysia,4.38195,102.40177,"6d 5n Tour Paradise Perhentian, Redang Island ...",3877.92,4.5
3,Kuala Tahan,transfers_ground_transport,19253545,Jerantut District,Malaysia,4.38195,102.40177,Chauffeur: Taman Negara to Singapore Transfer ...,489.86,4.5
4,Kuala Tahan,transfers_ground_transport,19253546,Jerantut District,Malaysia,4.38195,102.40177,Chauffeur: Taman Negara to Singapore Transfer ...,1524.04,4.5
5,Sepang,multiday_extended_tours,18910585,Sepang District,Malaysia,2.69093,101.75114,Luxurious Package to Malaysia with cheap price,4116.94,4.5
6,Sepang,multiday_extended_tours,17404431,Sepang District,Malaysia,2.69093,101.75114,A Passage Through Time,7195.37,4.5
7,Sepang,transfers_ground_transport,15340261,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport Arrival Transfer,71.29,4.5
8,Sepang,transfers_ground_transport,19281537,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Kuala Lumpur City Hotels,56.66,4.5
9,Sepang,transfers_ground_transport,19709350,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Malacca City Hotels EN...,185.45,4.5
10,Sepang,shopping_fashion,19496663,Sepang District,Malaysia,2.69093,101.75114,A Breath at Genting Highlands by MU Travel,412.11,4.5
11,Sepang,multiday_extended_tours,17404428,Sepang District,Malaysia,2.69093,101.75114,Flavours of Malaysia,8114.37,4.5
12,Sepang,multiday_extended_tours,17404429,Sepang District,Malaysia,2.69093,101.75114,Mesmerising Malaysia,6762.66,4.5
13,Sepang,multiday_extended_tours,17404430,Sepang District,Malaysia,2.69093,101.75114,Gems of Malaysia,4693.89,4.5
14,Sepang,walking_biking_tours,19496662,Sepang District,Malaysia,2.69093,101.75114,Amazing Kuala Lumpur Experience by MU Travel,403.86,4.5
15,Sepang,transfers_ground_transport,19714559,Sepang District,Malaysia,2.69093,101.75114,KLIA Ekspres Airport Train Tickets (QR Code Di...,67.92,4.5
16,Sepang,transfers_ground_transport,19380354,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport to Cameron ...,269.15,4.5
17,Sepang,shore_excursions,19267735,Sepang District,Malaysia,2.69093,101.75114,Go For A Tour Upon Arrival At Or During Depart...,412.11,4.0
18,Sepang,transfers_ground_transport,19380356,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport to Cameron Highlands City...,269.15,4.5
19,Sepang,multiday_extended_tours,13113673,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur 2 Night & 3 Days Package With Acc...,379.14,4.5
20,Sepang,transfers_ground_transport,19780484,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Penang City,406.95,4.5
21,Sepang,transfers_ground_transport,19780470,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Penang City,406.95,4.5
22,Sepang,transfers_ground_transport,19780473,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Penang City Hotels,406.95,4.5
23,Sepang,transfers_ground_transport,19442247,Sepang District,Malaysia,2.69093,101.75114,Get Car Sedan Kuala Lumpur Airport (KLIA) / KL...,112.78,4.5
24,Sepang,transfers_ground_transport,19281232,Sepang District,Malaysia,2.69093,101.75114,Private Kuala Lumpur Airport Transfers (Arrival),59.26,4.5
25,Sepang,transfers_ground_transport,19442499,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Kuala Lumpur City Hotels,47.68,4.5
26,Sepang,transfers_ground_transport,19442496,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Kuala Lu...,47.68,4.5
27,Sepang,transfers_ground_transport,19442492,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur City Hotels To Kuala Lumpur Airport,47.68,4.5
28,Sepang,transfers_ground_transport,19751792,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Intl Airport To Cameron Highlands...,417.26,4.5
29,Sepang,transfers_ground_transport,19758822,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Cameron ...,273.02,4.5
...,...,...,...,...,...,...,...,...,...,...
4227,Ipoh,tours_sightseeing,19780509,Kinta District,Malaysia,4.59725,101.12015,Best activity in Ipoh- Candid Photoshoot by Tr...,617.51,4.0
4228,Ipoh,transfers_ground_transport,17770269,Kinta District,Malaysia,4.59725,101.12015,Transfer: Ipoh to Kuala Lumpur International A...,218.77,4.5
4229,Ipoh,transfers_ground_transport,15045380,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotel to Kuala Lumpur Hotel (Door to Door...,346.17,4.5
4230,Ipoh,transfers_ground_transport,17770262,Kinta District,Malaysia,4.59725,101.12015,Transfer: Kuala Lumpur International Airport A...,218.77,4.5
4231,Ipoh,luxury_special_occasions,17829647,Kinta District,Malaysia,4.59725,101.12015,"Encounter With The Man Of The Forest At ""Orang...",655.34,4.0
4232,Ipoh,outdoor_activities,11771821,Kinta District,Malaysia,4.59725,101.12015,3.5-Hour Waterfall Abseiling Tour at Ulu Gerun...,179.62,4.5
4233,Ipoh,day_trips_excursions,13075309,Kinta District,Malaysia,4.59725,101.12015,Gopeng Day Trip,543.98,4.0
4234,Ipoh,luxury_special_occasions,17447504,Kinta District,Malaysia,4.59725,101.12015,Private Tour: Ipoh Secrets Full Day Heritage &...,529.66,4.0
4235,Ipoh,transfers_ground_transport,18909221,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur International Airport,206.05,4.5
4236,Ipoh,transfers_ground_transport,18909218,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotels to Kuala Lumpur Airport,206.05,4.5
4237,Ipoh,transfers_ground_transport,18909228,Kinta District,Malaysia,4.59725,101.12015,Ipoh City Hotels to Kuala Lumpur City1-way Tra...,206.05,4.5
4238,Ipoh,transfers_ground_transport,18909231,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur City Hotels 1-way Tr...,206.05,4.5
4239,Ipoh,transfers_ground_transport,18909237,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotels to Kuala Lumpur Airport,206.05,4.5
4240,Ipoh,transfers_ground_transport,18909239,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur International Airport,206.05,4.5
4241,Ipoh,transfers_ground_transport,18909241,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur City Hotels 1-way Tr...,206.05,4.5
4242,Ipoh,transfers_ground_transport,18909240,Kinta District,Malaysia,4.59725,101.12015,Ipoh City Hotels to Kuala Lumpur City1-way Tra...,206.05,4.5
4243,Pulau Tioman,shore_excursions,19709623,Rompin District,Malaysia,None,None,Scuba in Malaysia,144.24,4.0
4244,Pulau Tioman,water_sports,19773031,Rompin District,Malaysia,None,None,Scuba Diving Course Open Water,1203.35,4.0
4245,Putrajaya,walking_biking_tours,19645686,Wilayah Persekutuan,Malaysia,2.9365,101.69156,Putrajaya e-Bike Tours | Experience 1st e-Bicy...,61.82,5.0
4246,Sarawak,spa_tours,17681543,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 7-Nights Clarity and Peace of Mi...,13844.88,4.5
4247,Sarawak,spa_tours,17681544,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 3-Nights Clarity & Peace of Mind...,5933.52,4.5
4248,Sarawak,spa_tours,17681542,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 5-Nights Clarity & Peace of Mind...,9889.20,4.5
4249,Sarawak,multiday_extended_tours,12467423,Malaysia,Malaysia,2.310777,112.50697,3-Day Adventure in Mulu National Park,1312.97,4.0
4250,Sarawak,cultural_theme_tours,12467425,Malaysia,Malaysia,2.310777,112.50697,Historical Niah National Park Day Trip from Miri,300.63,4.0
4251,Sarawak,sightseeing_tickets_passes,15040428,Malaysia,Malaysia,2.310777,112.50697,Sarawak Gunung Gading National Park (Rafflesia...,338.75,4.0
4252,Sarawak,outdoor_activities,12467427,Malaysia,Malaysia,2.310777,112.50697,Half-Day Lambir Hills National Park Tour from ...,247.39,4.5
4253,Sarawak,tours_sightseeing,12467426,Malaysia,Malaysia,2.310777,112.50697,Half-Day Sightseeing Tour of Miri City,182.11,4.0
4254,Teluk Bahang,family_friendly,12934918,Penang Island,Malaysia,5.449866,100.21595,Entopia by Penang Butterfly Farm Official Admi...,59.44,5.0
4255,Teluk Bahang,theme_parks,13335655,Penang Island,Malaysia,5.449866,100.21595,ESCAPE Admission Ticket,166.49,5.0
4256,Teluk Bahang,cultural_theme_tours,11449718,Penang Island,Malaysia,5.449866,100.21595,Round Penang Island Tour,92.72,4.0

In [32]:
attr_rating_spark_df.createOrReplaceTempView('final_attr_spark_df')
final_attr_spark_df = attr_rating_spark_df

## Processing price

In [33]:
attr_price_spark_df = final_attr_spark_df

In [34]:
avg_price_spark_df = spark.sql(
    "SELECT city, AVG(price) as avg_price FROM final_attr_spark_df GROUP BY city"
)
avg_price_spark_df.show()

+-------------+------------------+
|         city|         avg_price|
+-------------+------------------+
|     Bongawan|            164.84|
|   Georgetown|             29.26|
|  Kuala Tahan|1963.9399999999998|
|       Sepang| 625.9777894736839|
|       Ampang|214.29500000000002|
|    Cherating| 379.7414999999999|
|  Kuala Kurau|            278.17|
|     Malaysia| 768.8152941176468|
|    Singapore|1902.5433333333333|
|   Katunayake|            280.23|
|      Beijing|            226.66|
|      Salalah|             214.3|
|       Melaka| 354.8621495327104|
|    Tamparuli|            185.45|
|Petaling Jaya| 265.3947500000002|
|  George Town| 328.2397101449276|
|  Kota Tinggi|             24.73|
|    Penampang|            232.84|
|      Sematan|           2357.25|
|  Bayan Lepas|206.87600000000003|
+-------------+------------------+
only showing top 20 rows

In [35]:
round_price_udf = functions.udf(lambda x: round(x, 2), DoubleType())

In [36]:
avg_price_spark_df = avg_price_spark_df.withColumn(
    'updated_price', round_price_udf(avg_price_spark_df["avg_price"]))
avg_price_spark_df.show()

+-------------+------------------+-------------+
|         city|         avg_price|updated_price|
+-------------+------------------+-------------+
|     Bongawan|            164.84|       164.84|
|   Georgetown|             29.26|        29.26|
|  Kuala Tahan|1963.9399999999998|      1963.94|
|       Sepang| 625.9777894736839|       625.98|
|       Ampang|214.29500000000002|        214.3|
|    Cherating| 379.7414999999999|       379.74|
|  Kuala Kurau|            278.17|       278.17|
|     Malaysia| 768.8152941176468|       768.82|
|    Singapore|1902.5433333333333|      1902.54|
|   Katunayake|            280.23|       280.23|
|      Beijing|            226.66|       226.66|
|      Salalah|             214.3|        214.3|
|       Melaka| 354.8621495327104|       354.86|
|    Tamparuli|            185.45|       185.45|
|Petaling Jaya| 265.3947500000002|       265.39|
|  George Town| 328.2397101449276|       328.24|
|  Kota Tinggi|             24.73|        24.73|
|    Penampang|            232.84|       232.84|
|      Sematan|           2357.25|      2357.25|
|  Bayan Lepas|206.87600000000003|       206.88|
+-------------+------------------+-------------+
only showing top 20 rows

In [37]:
attr_price_spark_df = attr_price_spark_df.join(avg_price_spark_df,
                                               ['city'],
                                               'left_outer')
attr_price_spark_df.count()

4257

In [38]:
attr_price_spark_df = attr_price_spark_df.withColumn(
    "price",
    functions.when(attr_price_spark_df["price"] == -1,
                   attr_price_spark_df["updated_price"]).otherwise(
                       attr_price_spark_df["price"])).drop(
                           'updated_price', 'avg_price')

In [39]:
# show null row from spark dataframe basec on specific column
attr_price_spark_df.where(attr_price_spark_df.price.isNull()).show()
attr_price_spark_df.count()

+----+--------+----------+-----+-------+--------+---------+----+-----+------+
|city|category|activityId|state|country|latitude|longitude|name|price|rating|
+----+--------+----------+-----+-------+--------+---------+----+-----+------+
+----+--------+----------+-----+-------+--------+---------+----+-----+------+

4257

In [40]:
display(attr_price_spark_df.toPandas())

,city,category,activityId,state,country,latitude,longitude,name,price,rating
0,Bongawan,cruises_sailing_water_tours,17683780,Sabah,Malaysia,5.507984,115.87458,Sky-Mirror Photographing and Proboscis Monkey...,164.84,5.0
1,Georgetown,sightseeing_tickets_passes,12990313,Demerara-Mahaica,Guyana,6.8,-58.1667,Colonial Penang Museum Admission Ticket,29.26,4.5
2,Kuala Tahan,multiday_extended_tours,14911433,Jerantut District,Malaysia,4.38195,102.40177,"6d 5n Tour Paradise Perhentian, Redang Island ...",3877.92,4.5
3,Kuala Tahan,transfers_ground_transport,19253545,Jerantut District,Malaysia,4.38195,102.40177,Chauffeur: Taman Negara to Singapore Transfer ...,489.86,4.5
4,Kuala Tahan,transfers_ground_transport,19253546,Jerantut District,Malaysia,4.38195,102.40177,Chauffeur: Taman Negara to Singapore Transfer ...,1524.04,4.5
5,Sepang,multiday_extended_tours,18910585,Sepang District,Malaysia,2.69093,101.75114,Luxurious Package to Malaysia with cheap price,4116.94,4.5
6,Sepang,multiday_extended_tours,17404431,Sepang District,Malaysia,2.69093,101.75114,A Passage Through Time,7195.37,4.5
7,Sepang,transfers_ground_transport,15340261,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport Arrival Transfer,71.29,4.5
8,Sepang,transfers_ground_transport,19281537,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Kuala Lumpur City Hotels,56.66,4.5
9,Sepang,transfers_ground_transport,19709350,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Malacca City Hotels EN...,185.45,4.5
10,Sepang,shopping_fashion,19496663,Sepang District,Malaysia,2.69093,101.75114,A Breath at Genting Highlands by MU Travel,412.11,4.5
11,Sepang,multiday_extended_tours,17404428,Sepang District,Malaysia,2.69093,101.75114,Flavours of Malaysia,8114.37,4.5
12,Sepang,multiday_extended_tours,17404429,Sepang District,Malaysia,2.69093,101.75114,Mesmerising Malaysia,6762.66,4.5
13,Sepang,multiday_extended_tours,17404430,Sepang District,Malaysia,2.69093,101.75114,Gems of Malaysia,4693.89,4.5
14,Sepang,walking_biking_tours,19496662,Sepang District,Malaysia,2.69093,101.75114,Amazing Kuala Lumpur Experience by MU Travel,403.86,4.5
15,Sepang,transfers_ground_transport,19714559,Sepang District,Malaysia,2.69093,101.75114,KLIA Ekspres Airport Train Tickets (QR Code Di...,67.92,4.5
16,Sepang,transfers_ground_transport,19380354,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport to Cameron ...,269.15,4.5
17,Sepang,shore_excursions,19267735,Sepang District,Malaysia,2.69093,101.75114,Go For A Tour Upon Arrival At Or During Depart...,412.11,4.0
18,Sepang,transfers_ground_transport,19380356,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport to Cameron Highlands City...,269.15,4.5
19,Sepang,multiday_extended_tours,13113673,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur 2 Night & 3 Days Package With Acc...,379.14,4.5
20,Sepang,transfers_ground_transport,19780484,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Penang City,406.95,4.5
21,Sepang,transfers_ground_transport,19780470,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Penang City,406.95,4.5
22,Sepang,transfers_ground_transport,19780473,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Penang City Hotels,406.95,4.5
23,Sepang,transfers_ground_transport,19442247,Sepang District,Malaysia,2.69093,101.75114,Get Car Sedan Kuala Lumpur Airport (KLIA) / KL...,112.78,4.5
24,Sepang,transfers_ground_transport,19281232,Sepang District,Malaysia,2.69093,101.75114,Private Kuala Lumpur Airport Transfers (Arrival),59.26,4.5
25,Sepang,transfers_ground_transport,19442499,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Kuala Lumpur City Hotels,47.68,4.5
26,Sepang,transfers_ground_transport,19442496,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Kuala Lu...,47.68,4.5
27,Sepang,transfers_ground_transport,19442492,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur City Hotels To Kuala Lumpur Airport,47.68,4.5
28,Sepang,transfers_ground_transport,19751792,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Intl Airport To Cameron Highlands...,417.26,4.5
29,Sepang,transfers_ground_transport,19758822,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Cameron ...,273.02,4.5
...,...,...,...,...,...,...,...,...,...,...
4227,Ipoh,tours_sightseeing,19780509,Kinta District,Malaysia,4.59725,101.12015,Best activity in Ipoh- Candid Photoshoot by Tr...,617.51,4.0
4228,Ipoh,transfers_ground_transport,17770269,Kinta District,Malaysia,4.59725,101.12015,Transfer: Ipoh to Kuala Lumpur International A...,218.77,4.5
4229,Ipoh,transfers_ground_transport,15045380,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotel to Kuala Lumpur Hotel (Door to Door...,346.17,4.5
4230,Ipoh,transfers_ground_transport,17770262,Kinta District,Malaysia,4.59725,101.12015,Transfer: Kuala Lumpur International Airport A...,218.77,4.5
4231,Ipoh,luxury_special_occasions,17829647,Kinta District,Malaysia,4.59725,101.12015,"Encounter With The Man Of The Forest At ""Orang...",655.34,4.0
4232,Ipoh,outdoor_activities,11771821,Kinta District,Malaysia,4.59725,101.12015,3.5-Hour Waterfall Abseiling Tour at Ulu Gerun...,179.62,4.5
4233,Ipoh,day_trips_excursions,13075309,Kinta District,Malaysia,4.59725,101.12015,Gopeng Day Trip,543.98,4.0
4234,Ipoh,luxury_special_occasions,17447504,Kinta District,Malaysia,4.59725,101.12015,Private Tour: Ipoh Secrets Full Day Heritage &...,529.66,4.0
4235,Ipoh,transfers_ground_transport,18909221,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur International Airport,206.05,4.5
4236,Ipoh,transfers_ground_transport,18909218,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotels to Kuala Lumpur Airport,206.05,4.5
4237,Ipoh,transfers_ground_transport,18909228,Kinta District,Malaysia,4.59725,101.12015,Ipoh City Hotels to Kuala Lumpur City1-way Tra...,206.05,4.5
4238,Ipoh,transfers_ground_transport,18909231,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur City Hotels 1-way Tr...,206.05,4.5
4239,Ipoh,transfers_ground_transport,18909237,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotels to Kuala Lumpur Airport,206.05,4.5
4240,Ipoh,transfers_ground_transport,18909239,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur International Airport,206.05,4.5
4241,Ipoh,transfers_ground_transport,18909241,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur City Hotels 1-way Tr...,206.05,4.5
4242,Ipoh,transfers_ground_transport,18909240,Kinta District,Malaysia,4.59725,101.12015,Ipoh City Hotels to Kuala Lumpur City1-way Tra...,206.05,4.5
4243,Pulau Tioman,shore_excursions,19709623,Rompin District,Malaysia,None,None,Scuba in Malaysia,144.24,4.0
4244,Pulau Tioman,water_sports,19773031,Rompin District,Malaysia,None,None,Scuba Diving Course Open Water,1203.35,4.0
4245,Putrajaya,walking_biking_tours,19645686,Wilayah Persekutuan,Malaysia,2.9365,101.69156,Putrajaya e-Bike Tours | Experience 1st e-Bicy...,61.82,5.0
4246,Sarawak,spa_tours,17681543,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 7-Nights Clarity and Peace of Mi...,13844.88,4.5
4247,Sarawak,spa_tours,17681544,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 3-Nights Clarity & Peace of Mind...,5933.52,4.5
4248,Sarawak,spa_tours,17681542,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 5-Nights Clarity & Peace of Mind...,9889.20,4.5
4249,Sarawak,multiday_extended_tours,12467423,Malaysia,Malaysia,2.310777,112.50697,3-Day Adventure in Mulu National Park,1312.97,4.0
4250,Sarawak,cultural_theme_tours,12467425,Malaysia,Malaysia,2.310777,112.50697,Historical Niah National Park Day Trip from Miri,300.63,4.0
4251,Sarawak,sightseeing_tickets_passes,15040428,Malaysia,Malaysia,2.310777,112.50697,Sarawak Gunung Gading National Park (Rafflesia...,338.75,4.0
4252,Sarawak,outdoor_activities,12467427,Malaysia,Malaysia,2.310777,112.50697,Half-Day Lambir Hills National Park Tour from ...,247.39,4.5
4253,Sarawak,tours_sightseeing,12467426,Malaysia,Malaysia,2.310777,112.50697,Half-Day Sightseeing Tour of Miri City,182.11,4.0
4254,Teluk Bahang,family_friendly,12934918,Penang Island,Malaysia,5.449866,100.21595,Entopia by Penang Butterfly Farm Official Admi...,59.44,5.0
4255,Teluk Bahang,theme_parks,13335655,Penang Island,Malaysia,5.449866,100.21595,ESCAPE Admission Ticket,166.49,5.0
4256,Teluk Bahang,cultural_theme_tours,11449718,Penang Island,Malaysia,5.449866,100.21595,Round Penang Island Tour,92.72,4.0

In [41]:
attr_price_spark_df.createOrReplaceTempView('final_attr_spark_df')
final_attr_spark_df = attr_price_spark_df

## Processing geo coordinates

In [63]:
attr_geo_spark_df = final_attr_spark_df

In [64]:
avg_geo_spark_df = spark.sql(
    "SELECT city, AVG(latitude) as avg_lat, AVG(longitude) as avg_lng FROM final_attr_spark_df GROUP BY city"
)
avg_geo_spark_df.show()

+-------------+------------------+------------------+
|         city|           avg_lat|           avg_lng|
+-------------+------------------+------------------+
|     Bongawan|          5.507984|         115.87458|
|   Georgetown|               6.8|          -58.1667|
|  Kuala Tahan|           4.38195|         102.40177|
|       Sepang|2.6909300000000034|101.75114000000015|
|       Ampang|          3.156205|         101.75031|
|    Cherating|          4.133792|103.38025999999995|
|  Kuala Kurau|          5.018007|         100.43176|
|     Malaysia| 3.480286999999999|102.47243000000002|
|    Singapore|1.2858009999999995|103.85111000000005|
|   Katunayake|           7.15966|          79.87023|
|      Beijing|         39.909336|         116.39452|
|      Salalah|          17.01493|          54.09302|
|       Melaka|2.2068470000000033|102.25326999999989|
|    Tamparuli|           6.13333|         116.26667|
|Petaling Jaya|3.1036300000000066| 101.6477799999997|
|  George Town| 5.411938000000005|100.32664000000015|
|  Kota Tinggi|           1.72844|         103.89902|
|    Penampang|          5.877649|          116.1034|
|      Sematan|           1.79517|         109.75138|
|  Bayan Lepas|          5.294487|         100.25968|
+-------------+------------------+------------------+
only showing top 20 rows

In [65]:
attr_geo_spark_df = attr_geo_spark_df.join(avg_geo_spark_df, ['city'],
                                           'left_outer')
attr_geo_spark_df.count()

4257

In [66]:
attr_geo_spark_df = attr_geo_spark_df.withColumn(
    'latitude',
    functions.when(attr_geo_spark_df['latitude'].isNull(),
                   attr_geo_spark_df['avg_lat']).otherwise(
                       attr_geo_spark_df['latitude'])).withColumn(
                           'longitude',
                           functions.when(
                               attr_geo_spark_df['longitude'].isNull(),
                               attr_geo_spark_df['avg_lng']).otherwise(
                                   attr_geo_spark_df['longitude'])).drop(
                                       attr_geo_spark_df['avg_lat']).drop(
                                           attr_geo_spark_df['avg_lng'])

In [67]:
# show null row from spark dataframe basec on specific column
display(
    attr_geo_spark_df.where(attr_geo_spark_df.latitude.isNull()).toPandas())
display(
    attr_geo_spark_df.where(attr_geo_spark_df.longitude.isNull()).toPandas())
attr_geo_spark_df.count()

,city,category,activityId,state,country,latitude,longitude,name,price,rating
0,Pulau Tioman,shore_excursions,19709623,Rompin District,Malaysia,None,None,Scuba in Malaysia,144.24,4.0
1,Pulau Tioman,water_sports,19773031,Rompin District,Malaysia,None,None,Scuba Diving Course Open Water,1203.35,4.0

,city,category,activityId,state,country,latitude,longitude,name,price,rating
0,Pulau Tioman,shore_excursions,19709623,Rompin District,Malaysia,None,None,Scuba in Malaysia,144.24,4.0
1,Pulau Tioman,water_sports,19773031,Rompin District,Malaysia,None,None,Scuba Diving Course Open Water,1203.35,4.0

4257

###### Get the geocode for empty latitude and longitude fields

In [68]:
import googlemaps
import os

In [69]:
def get_geocode(place):
    gmaps = googlemaps.Client(key=os.environ['GOOGLE_API_KEY'])
    place = gmaps.places(place)
    geocode = {
        'lat': place["results"][0]["geometry"]["location"]["lat"],
        'lng': place["results"][0]["geometry"]["location"]["lng"]
    }
    return geocode

In [70]:
get_lat_udf = functions.udf(lambda x: get_geocode(x)['lat'], StringType())
get_lng_udf = functions.udf(lambda x: get_geocode(x)['lng'], StringType())

In [71]:
temp_geo_spark_df = attr_geo_spark_df.where(attr_geo_spark_df.latitude.isNull())
temp_geo_spark_df.count()
display(temp_geo_spark_df.toPandas())

,city,category,activityId,state,country,latitude,longitude,name,price,rating
0,Pulau Tioman,shore_excursions,19709623,Rompin District,Malaysia,None,None,Scuba in Malaysia,144.24,4.0
1,Pulau Tioman,water_sports,19773031,Rompin District,Malaysia,None,None,Scuba Diving Course Open Water,1203.35,4.0

In [72]:
temp_geo_spark_df = temp_geo_spark_df.where(
    temp_geo_spark_df.latitude.isNull()).withColumn(
        "latitude", get_lat_udf(temp_geo_spark_df.city))

temp_geo_spark_df = temp_geo_spark_df.where(
    temp_geo_spark_df.longitude.isNull()).withColumn(
        "longitude", get_lng_udf(temp_geo_spark_df.city))

In [73]:
temp_geo_spark_df = temp_geo_spark_df.toPandas()
temp_geo_spark_df.head()

,city,category,activityId,state,country,latitude,longitude,name,price,rating
0,Pulau Tioman,shore_excursions,19709623,Rompin District,Malaysia,2.7902494,104.1698463,Scuba in Malaysia,144.24,4.0
1,Pulau Tioman,water_sports,19773031,Rompin District,Malaysia,2.7902494,104.1698463,Scuba Diving Course Open Water,1203.35,4.0

In [75]:
temp_geo_spark_df = spark.createDataFrame(temp_geo_spark_df)

In [76]:
attr_geo_spark_df = attr_geo_spark_df.where(attr_geo_spark_df.latitude.isNotNull()).union(temp_geo_spark_df)
attr_geo_spark_df.count()

4257

In [77]:
# show null row from spark dataframe basec on specific column
display(
    attr_geo_spark_df.where(attr_geo_spark_df.latitude.isNull()).toPandas())
display(
    attr_geo_spark_df.where(attr_geo_spark_df.longitude.isNull()).toPandas())
attr_geo_spark_df.count()

Empty DataFrame
Columns: [city, category, activityId, state, country, latitude, longitude, name, price, rating]
Index: []

Empty DataFrame
Columns: [city, category, activityId, state, country, latitude, longitude, name, price, rating]
Index: []

4257

In [78]:
display(attr_geo_spark_df.toPandas())

,city,category,activityId,state,country,latitude,longitude,name,price,rating
0,Bongawan,cruises_sailing_water_tours,17683780,Sabah,Malaysia,5.507984,115.87458,Sky-Mirror Photographing and Proboscis Monkey...,164.84,5.0
1,Georgetown,sightseeing_tickets_passes,12990313,Demerara-Mahaica,Guyana,6.8,-58.1667,Colonial Penang Museum Admission Ticket,29.26,4.5
2,Kuala Tahan,multiday_extended_tours,14911433,Jerantut District,Malaysia,4.38195,102.40177,"6d 5n Tour Paradise Perhentian, Redang Island ...",3877.92,4.5
3,Kuala Tahan,transfers_ground_transport,19253545,Jerantut District,Malaysia,4.38195,102.40177,Chauffeur: Taman Negara to Singapore Transfer ...,489.86,4.5
4,Kuala Tahan,transfers_ground_transport,19253546,Jerantut District,Malaysia,4.38195,102.40177,Chauffeur: Taman Negara to Singapore Transfer ...,1524.04,4.5
5,Sepang,multiday_extended_tours,18910585,Sepang District,Malaysia,2.69093,101.75114,Luxurious Package to Malaysia with cheap price,4116.94,4.5
6,Sepang,multiday_extended_tours,17404431,Sepang District,Malaysia,2.69093,101.75114,A Passage Through Time,7195.37,4.5
7,Sepang,transfers_ground_transport,15340261,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport Arrival Transfer,71.29,4.5
8,Sepang,transfers_ground_transport,19281537,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Kuala Lumpur City Hotels,56.66,4.5
9,Sepang,transfers_ground_transport,19709350,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Malacca City Hotels EN...,185.45,4.5
10,Sepang,shopping_fashion,19496663,Sepang District,Malaysia,2.69093,101.75114,A Breath at Genting Highlands by MU Travel,412.11,4.5
11,Sepang,multiday_extended_tours,17404428,Sepang District,Malaysia,2.69093,101.75114,Flavours of Malaysia,8114.37,4.5
12,Sepang,multiday_extended_tours,17404429,Sepang District,Malaysia,2.69093,101.75114,Mesmerising Malaysia,6762.66,4.5
13,Sepang,multiday_extended_tours,17404430,Sepang District,Malaysia,2.69093,101.75114,Gems of Malaysia,4693.89,4.5
14,Sepang,walking_biking_tours,19496662,Sepang District,Malaysia,2.69093,101.75114,Amazing Kuala Lumpur Experience by MU Travel,403.86,4.5
15,Sepang,transfers_ground_transport,19714559,Sepang District,Malaysia,2.69093,101.75114,KLIA Ekspres Airport Train Tickets (QR Code Di...,67.92,4.5
16,Sepang,transfers_ground_transport,19380354,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport to Cameron ...,269.15,4.5
17,Sepang,shore_excursions,19267735,Sepang District,Malaysia,2.69093,101.75114,Go For A Tour Upon Arrival At Or During Depart...,412.11,4.0
18,Sepang,transfers_ground_transport,19380356,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport to Cameron Highlands City...,269.15,4.5
19,Sepang,multiday_extended_tours,13113673,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur 2 Night & 3 Days Package With Acc...,379.14,4.5
20,Sepang,transfers_ground_transport,19780484,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Penang City,406.95,4.5
21,Sepang,transfers_ground_transport,19780470,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Penang City,406.95,4.5
22,Sepang,transfers_ground_transport,19780473,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Penang City Hotels,406.95,4.5
23,Sepang,transfers_ground_transport,19442247,Sepang District,Malaysia,2.69093,101.75114,Get Car Sedan Kuala Lumpur Airport (KLIA) / KL...,112.78,4.5
24,Sepang,transfers_ground_transport,19281232,Sepang District,Malaysia,2.69093,101.75114,Private Kuala Lumpur Airport Transfers (Arrival),59.26,4.5
25,Sepang,transfers_ground_transport,19442499,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Airport To Kuala Lumpur City Hotels,47.68,4.5
26,Sepang,transfers_ground_transport,19442496,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Kuala Lu...,47.68,4.5
27,Sepang,transfers_ground_transport,19442492,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur City Hotels To Kuala Lumpur Airport,47.68,4.5
28,Sepang,transfers_ground_transport,19751792,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur Intl Airport To Cameron Highlands...,417.26,4.5
29,Sepang,transfers_ground_transport,19758822,Sepang District,Malaysia,2.69093,101.75114,Kuala Lumpur International Airport To Cameron ...,273.02,4.5
...,...,...,...,...,...,...,...,...,...,...
4227,Ipoh,tours_sightseeing,19780509,Kinta District,Malaysia,4.59725,101.12015,Best activity in Ipoh- Candid Photoshoot by Tr...,617.51,4.0
4228,Ipoh,transfers_ground_transport,17770269,Kinta District,Malaysia,4.59725,101.12015,Transfer: Ipoh to Kuala Lumpur International A...,218.77,4.5
4229,Ipoh,transfers_ground_transport,15045380,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotel to Kuala Lumpur Hotel (Door to Door...,346.17,4.5
4230,Ipoh,transfers_ground_transport,17770262,Kinta District,Malaysia,4.59725,101.12015,Transfer: Kuala Lumpur International Airport A...,218.77,4.5
4231,Ipoh,luxury_special_occasions,17829647,Kinta District,Malaysia,4.59725,101.12015,"Encounter With The Man Of The Forest At ""Orang...",655.34,4.0
4232,Ipoh,outdoor_activities,11771821,Kinta District,Malaysia,4.59725,101.12015,3.5-Hour Waterfall Abseiling Tour at Ulu Gerun...,179.62,4.5
4233,Ipoh,day_trips_excursions,13075309,Kinta District,Malaysia,4.59725,101.12015,Gopeng Day Trip,543.98,4.0
4234,Ipoh,luxury_special_occasions,17447504,Kinta District,Malaysia,4.59725,101.12015,Private Tour: Ipoh Secrets Full Day Heritage &...,529.66,4.0
4235,Ipoh,transfers_ground_transport,18909221,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur International Airport,206.05,4.5
4236,Ipoh,transfers_ground_transport,18909218,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotels to Kuala Lumpur Airport,206.05,4.5
4237,Ipoh,transfers_ground_transport,18909228,Kinta District,Malaysia,4.59725,101.12015,Ipoh City Hotels to Kuala Lumpur City1-way Tra...,206.05,4.5
4238,Ipoh,transfers_ground_transport,18909231,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur City Hotels 1-way Tr...,206.05,4.5
4239,Ipoh,transfers_ground_transport,18909237,Kinta District,Malaysia,4.59725,101.12015,Ipoh Hotels to Kuala Lumpur Airport,206.05,4.5
4240,Ipoh,transfers_ground_transport,18909239,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur International Airport,206.05,4.5
4241,Ipoh,transfers_ground_transport,18909241,Kinta District,Malaysia,4.59725,101.12015,Ipoh City to Kuala Lumpur City Hotels 1-way Tr...,206.05,4.5
4242,Ipoh,transfers_ground_transport,18909240,Kinta District,Malaysia,4.59725,101.12015,Ipoh City Hotels to Kuala Lumpur City1-way Tra...,206.05,4.5
4243,Putrajaya,walking_biking_tours,19645686,Wilayah Persekutuan,Malaysia,2.9365,101.69156,Putrajaya e-Bike Tours | Experience 1st e-Bicy...,61.82,5.0
4244,Sarawak,spa_tours,17681543,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 7-Nights Clarity and Peace of Mi...,13844.88,4.5
4245,Sarawak,spa_tours,17681544,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 3-Nights Clarity & Peace of Mind...,5933.52,4.5
4246,Sarawak,spa_tours,17681542,Malaysia,Malaysia,2.310777,112.50697,Ayus Wellness 5-Nights Clarity & Peace of Mind...,9889.20,4.5
4247,Sarawak,multiday_extended_tours,12467423,Malaysia,Malaysia,2.310777,112.50697,3-Day Adventure in Mulu National Park,1312.97,4.0
4248,Sarawak,cultural_theme_tours,12467425,Malaysia,Malaysia,2.310777,112.50697,Historical Niah National Park Day Trip from Miri,300.63,4.0
4249,Sarawak,sightseeing_tickets_passes,15040428,Malaysia,Malaysia,2.310777,112.50697,Sarawak Gunung Gading National Park (Rafflesia...,338.75,4.0
4250,Sarawak,outdoor_activities,12467427,Malaysia,Malaysia,2.310777,112.50697,Half-Day Lambir Hills National Park Tour from ...,247.39,4.5
4251,Sarawak,tours_sightseeing,12467426,Malaysia,Malaysia,2.310777,112.50697,Half-Day Sightseeing Tour of Miri City,182.11,4.0
4252,Teluk Bahang,family_friendly,12934918,Penang Island,Malaysia,5.449866,100.21595,Entopia by Penang Butterfly Farm Official Admi...,59.44,5.0
4253,Teluk Bahang,theme_parks,13335655,Penang Island,Malaysia,5.449866,100.21595,ESCAPE Admission Ticket,166.49,5.0
4254,Teluk Bahang,cultural_theme_tours,11449718,Penang Island,Malaysia,5.449866,100.21595,Round Penang Island Tour,92.72,4.0
4255,Pulau Tioman,shore_excursions,19709623,Rompin District,Malaysia,2.7902494,104.1698463,Scuba in Malaysia,144.24,4.0
4256,Pulau Tioman,water_sports,19773031,Rompin District,Malaysia,2.7902494,104.1698463,Scuba Diving Course Open Water,1203.35,4.0

In [79]:
attr_geo_spark_df.createOrReplaceTempView('final_attr_spark_df')
final_attr_spark_df = attr_geo_spark_df

## Saving Attraction Details

In [80]:
final_attr_spark_df.coalesce(8).write.parquet(parquet_path + 'etl/attractions',
                                              mode='overwrite')

In [81]:
final_attr_spark_df.coalesce(1).write.format('json').save(
    parquet_path + 'etl/attractions/json', mode='overwrite')

# Attraction Review

In [5]:
# define path
tripad_attr_path = ROOT_DIR + '/crawler/datasets/tripadvisor_dataset/attractions/'
parquet_path = ROOT_DIR + '/crawler/datasets/tripadvisor_dataset/spark/'

In [6]:
# read spark dataframe from parquet
attr_review_spark_df = spark.read.parquet(parquet_path + 'tripad_attr_review').repartition(160)
attr_review_spark_df.count()

7146

In [7]:
attr_review_spark_df = attr_review_spark_df.select(
    attr_review_spark_df.activityId.cast("string"), attr_review_spark_df.rating,
    attr_review_spark_df.text.alias('review'),
    attr_review_spark_df.publishedDate.alias('review_date'),
    attr_review_spark_df.username.alias('user'), attr_review_spark_df.userId)

In [8]:
attr_review_df = attr_review_spark_df.toPandas()
attr_review_df['user_id'] = attr_review_df.index

In [9]:
display(attr_review_df)

,activityId,rating,review,review_date,user,userId,user_id
0,11449677,4,Very good Bus tour with a great guide/speaker ...,2018-02-12,Vincent W,BB0401B4A7E786BCB80F6A34F9CA7CD5,0
1,12880465,5,This was our second visit to KL and we had tic...,2018-10-19,DarrenCBristol,37060EBD1EB824EBB6E8E70215D27C70,1
2,16722683,5,Cheap way to see main highlights of KL. Hop on...,2016-10-27,BudiMohdYunus,08C1EDB33313D195676C1334F800272C,2
3,12468919,5,"Zoo is not my usual favourite, but I must say ...",2018-09-29,amyrosylily,7048960540A76440C6BCA16D4B0D649B,3
4,12650625,5,It was an enjoyable ride with great scenary wi...,2019-06-07,LakeGardenEcoRide,27721A880DA255F34D797EDAF03D28E5,4
5,11454341,5,We booked the jet skiing experience the day be...,2018-02-10,alic1988,3D56FCDC833D0F6E4CE6410A56964CB9,5
6,16722683,5,We went in the hop on off bus on a very hot da...,2016-09-29,Bubbles W,1BC5DBF5897A853A5A3A7F06B1D60B44,6
7,16722683,2,Having travelled on a number of Hop on Hop off...,2015-05-18,rhondda1,07972311330CF222252B246D4E8DE087,7
8,12943485,5,Its was very challenging and fun! The staff ar...,2019-10-08,njlaaaa,08538AF0DDAE4466DA16EBC29ABC32F0,8
9,17404880,4,Had a lot of fun even for first timer ! Suitab...,2019-10-07,Zettyzulkifli,89EC1E138DAEBFF018D741F86CD84260,9
10,17823853,5,Me and my boys signed up for a session each. W...,2019-12-22,great_geok,004CC226A0AA8C661B0C355DFA946B62,10
11,11452241,5,Highly recommend the tour if you want to eat l...,2019-04-18,Lina M,3719A741B9D373C9764EA63117238575,11
12,16722683,4,I'm honestly surprised by all the bad reviews....,2016-05-30,Geo89_12,D669DBB55BC7B2CCFF6D484503807675,12
13,15126852,5,I went on the magical river trek with Chen and...,2015-05-25,Matthias0803,B17C6D1F6DDCA24E72E8624EE7C2E8BD,13
14,12467422,5,I escorted two clients and a student after a m...,2019-08-06,sharkstewards,A8A8E70AACF0A6A5CF366AEF0DE89376,14
15,15142299,4,We booked this tour before arriving in KK and ...,2019-09-02,dawny66,B6587C51B63279E87846581CC5D726D2,15
16,12471375,4,Cable ride was beautiful but it was a waste of...,2019-11-12,AshokKJain,A4962017D393E159BABCAEEAD5C58EA5,16
17,13131236,2,Didn't get to ride it and had to pay for parki...,2019-09-04,Wendofish,58F5EE3FB9C408582E25216A66BF6FE8,17
18,15633618,5,I did a 'Hidden secrets of KL' bike tour with ...,2019-07-16,ddmeyst,C12ED733A00DC8C521C1C6B4F018F870,18
19,16722683,3,This is not intended as a criticism of the ope...,2018-09-28,willettbrian,C764E27E493BB35B493B986C3AB9F5AA,19
20,11486172,5,Six of us took a great food tour with Heritage...,2019-02-04,Robert B,AECA393C909852CE6EAD87903E5DB246,20
21,13335655,5,Great for families. Has both exhilarating and ...,2019-09-03,Menkau,CC54D68228433C005BCF12AAF4B627E6,21
22,17575314,5,Guides are helpful and professional. We had fu...,2019-12-15,wywsyy,5538603A4744136EC8DE93E48D654B64,22
23,11449728,5,One of the best customer service from Julkifli...,2019-12-20,Jenson_chai_04,3C9A63DA7201D6227D4D01CE4C6EE321,23
24,16722683,3,This bus tour is a great way to see all of the...,2015-07-06,CityTraveler1802,CE60535D5CF303A2ECF614BC8D5510B5,24
25,12470242,5,We had so much fun on this tour! It was better...,2019-11-15,Meaghan G,DFB749047CFB95CF4F5E17A5AAC2D460,25
26,13335655,5,The trip to escape theme park in Penang was a ...,2019-07-05,154keshg,ED6F2906D7821867B79B3076CCCBBE55,26
27,11856870,5,We booked a day's scuba diving with Diverse Bo...,2018-09-29,Andrew T,B63BDA06EC35B963686DC3EAD9BBF4E8,27
28,16722683,1,We typically love hop on hop off tours because...,2019-06-13,Susie S,1CCD863EBA4ED10028E803D9B7A3A481,28
29,19149426,5,Started with an early morning pickup from our ...,2019-11-23,patha93,BB823F2B2CE8EBC360D2E6534F118AA0,29
...,...,...,...,...,...,...,...
7116,17447504,4,We had a great day with guide John. We were 5 ...,2019-08-04,marcusnl2018,2102898CFD7B807B34BA6730CA201C8E,7116
7117,12471352,5,"The trip was so nice, and the guide Mr. Maron ...",2019-12-17,Ahmed E,C33E9C1D535F21A4621C74025D85A31D,7117
7118,11471521,5,"Did the Best of Kuching ride with Bansik, a ve...",2019-07-11,Gpjsesas,CAFEA251ECC6BC54FAA57C452ECE6B1E,7118
7119,17516625,5,huh ， whole day raining even pouring for one h...,2019-06-18,Alice1540538913,9DF3B7E1B73DA77E3FEC73D858FF1659,7119
7120,13088933,5,Wow! I can honestly say I’ve never experienced...,2019-04-29,ALV710,0BCA88E70E96BB1818C206F30B675A96,7120
7121,16722683,2,"u will take it for abt 35 myr, it will show so...",2012-11-05,11khaled_12,4FBC56E889A4CD4A692246A493BC7962,7121
7122,11449728,5,Best experience ever to visit here... Here so...,2019-11-09,SyamanUnimap,140DF66EC75A7E22BEFA57806AB0AFE6,7122
7123,11991714,5,First off this is a safe and cool way to view ...,2012-04-14,gurple,632E29CB11BBFC7C9B3724A487EEF0D5,7123
7124,12905660,5,\nBuy your ticket online before the visit.Brea...,2018-12-28,190sathiap,2C18016322C75CDE6D54AB4EE98CD33C,7124
7125,11449677,5,Great 1/2 tour of Kuala Lumpur. Saw the King’s...,2019-10-10,Jls5189,25BE122AAA1383607BEDCF69AE906A2E,7125
7126,11452241,5,Greetings. If you ever find yourself in kuala ...,2018-03-26,Arshad A,7BFF03A837B29A289E279D75153F0AC2,7126
7127,13335655,5,First I would like to truly appreciate the sta...,2019-10-11,daryl0419,75BF42577D4F1CF122EEC6FC6908C903,7127
7128,15678609,5,I found out in the morning that i will be the ...,2019-12-21,Saara L,0CE554008D7017B350151CE7B7D63F7B,7128
7129,11474972,5,We booked the half day cycling tour via intern...,2018-12-24,VickyDimi,DF0582F0A6359BDDED6C84517CBC680B,7129
7130,12074338,5,I did a three hour tour with Delish today. My ...,2019-04-22,Roboduck999,0A56B03B4240E267A6812A6A17BA8341,7130
7131,11991123,5,"The property's uniqueness stands on its own, b...",2019-11-08,Jose A,6F2F5877864542D7A27D36270AFE26F7,7131
7132,11449679,5,The huge statue of Budha was awe inspiring - w...,2018-01-22,KissimmeeKissimmee,0E3744C4DCF2A04418C2D7986E921934,7132
7133,11467596,5,Excellent kayaking tour with our knowledgeable...,2019-12-29,graphicalphabet,F51AE8858E4983F7AEA68DB17D3EC9F3,7133
7134,11470871,5,This was my first-ever experience flying with ...,2018-08-27,Dennis C,59A01B791680FE1B99FE29CD15A889F8,7134
7135,11812461,5,Great morning and lunch with Brendon. Everythi...,2019-01-22,jobaut,4D49B223A23DDAFEA790E65168804555,7135
7136,17419599,5,My girlfriend and I did this tour during our v...,2019-03-29,leokita,314806AC8C3139B6D9214167F1D4C315,7136
7137,16804447,4,My sister and I attended the cooking class and...,2019-08-17,Rachelgracem99,C8641CF46FDDD7A9B4A612EBBA8E724E,7137
7138,14128357,5,What a great experience! Quick and easy from t...,2019-06-12,ChrisH5363,FE52FE0D0E7C1565E71E3E5167A874C4,7138
7139,16823284,5,We had a great experience om the Wetland Wildl...,2019-09-11,RenzaV2,D9F3E6CD35D3F6AFB36DCCC94C6DD397,7139
7140,14861251,5,I visited Malaysia for a 3 days official tour ...,2015-06-16,JMJKumar,9A5CCF4D48ABE2A5661327121D6FF0F9,7140
7141,11450590,4,"Variety of food and beverage, clean, comfortab...",2019-10-25,NadiaR1486,62365754C0F45C6F5E70C47A5600BB41,7141
7142,17566121,5,Superb Rafting activity. \nTeam so great with ...,2019-12-28,Sadoko U,B4B463010862690CA5FCC5073EE4F6D7,7142
7143,11854369,3,You can book this from one of the many street ...,2019-09-06,De80rah,3A8289D916726878BA82BB02DBD76B8B,7143
7144,11449679,5,This tour is totally worth it. The Batu caves ...,2019-10-09,nvkm68,08E9B7E46CBFE872B8F2E4AD2DDEBD7D,7144
7145,12061739,1,What should have been an enjoyable and enlight...,2018-11-11,Wrigginger,EC5BF24D3B87C4F6D23DC81DCD6C77E8,7145

In [10]:
attr_review_spark_df = spark.createDataFrame(attr_review_df)

In [11]:
attr_review_spark_df.createOrReplaceTempView('attr_review_spark_df')

In [12]:
user_rev_count = spark.sql("SELECT user, COUNT(*) as rev_count FROM attr_review_spark_df GROUP BY user ORDER BY rev_count DESC")
user_rev_count.count()

6684

In [13]:
print("Reviews are available for {attr_count} attractions.".format(
    attr_count=len(
        attr_review_spark_df.select('activityId').distinct().collect())))
print(
    "Matrix will be highly sparse as the maximum number of reviews provided by an user is {val}."
    .format(val=user_rev_count.select('rev_count').limit(1).collect()[0][0]))

Reviews are available for 696 attractions.
Matrix will be highly sparse as the maximum number of reviews provided by an user is 12.

## Saving Attraction Reviews

In [14]:
attr_review_spark_df.coalesce(8).write.parquet(parquet_path +
                                               'etl/attraction_reviews',
                                               mode='overwrite')

In [15]:
attr_review_spark_df.coalesce(1).write.format('json').save(
    parquet_path + 'etl/attraction_reviews/json', mode='overwrite')